# Code for the adapter that transforms the output of the lexer into a format compatible with PLY's expectations.

class LexToken:
    # Class to simulate the structure of a native PLY token.
    pass

KEYWORD_MAP = {
    'int': 'INT',
    'float': 'FLOAT',
    'double': 'DOUBLE',
    'char': 'CHAR',
    'void': 'VOID',
    'if': 'IF',
    'else': 'ELSE',
    'while': 'WHILE',
    'for': 'FOR',
    'return': 'RETURN',
}


OPERATOR_MAP = {
    '=': 'ASSIGN',
    '+=': 'ADD_ASSIGN',
    '-=': 'SUB_ASSIGN',
    '/=': 'DIV_ASSIGN',
    '++': 'INC',
    '--': 'DEC',
    '+': 'PLUS',
    '-': 'MINUS',
    '*': 'TIMES',
    '/': 'DIVIDE',
    '%': 'MOD',
    '==': 'EQ',
    '!=': 'NE',
    '<': 'LT',
    '<=': 'LE',
    '>': 'GT',
    '>=': 'GE',
    '&&': 'AND',
    '||': 'OR',
    '!': 'NOT',
}


PUNCTUATION_MAP = {
    ';': 'SEMICOLON',
    ',': 'COMMA',
    '(': 'LPAREN',
    ')': 'RPAREN',
    '{': 'LBRACE',
    '}': 'RBRACE',
}

class PlyLexerAdapter:
    def __init__(self, tokens_list, source_code=""):
        # Get the list generated by the lexer and converts it into an iterator for the parser
        self.tokens_list = self._normalize_tokens(tokens_list)
        self.iterator = iter(self.tokens_list)
        self.lineno = 1
        self.lexpos = 0
        self.index = 0
        self.positions = self._build_positions(source_code)

    def _normalize_tokens(self, tokens_list):
        normalized = []
        i = 0

        while i < len(tokens_list):
            category, value = tokens_list[i]

            if i + 1 < len(tokens_list):
                next_category, next_value = tokens_list[i + 1]

                # Compound assignment and inc/dec when lexer splits operator tokens.
                if category == 'OPERATOR' and next_category == 'OPERATOR':
                    pair = value + next_value
                    if pair in {'++', '--', '+=', '-=', '/=', '==', '!=', '<=', '>=', '||'}:
                        normalized.append(('OPERATOR', pair))
                        i += 2
                        continue

                # Logical AND when lexer emits '&' '&' as SPECIAL tokens.
                if category == 'SPECIAL' and next_category == 'SPECIAL' and value == '&' and next_value == '&':
                    normalized.append(('OPERATOR', '&&'))
                    i += 2
                    continue

            normalized.append((category, value))
            i += 1

        return normalized

    def _build_positions(self, source_code):
        positions = []
        cursor = 0
        line = 1

        for _, value in self.tokens_list:
            if source_code:
                idx = source_code.find(value, cursor)
                if idx < 0:
                    idx = cursor

                skipped = source_code[cursor:idx]
                line += skipped.count('\n')
                tok_line = line
                tok_lexpos = idx

                line += value.count('\n')
                cursor = idx + len(value)
            else:
                tok_line = line
                tok_lexpos = cursor
                line += value.count('\n')
                cursor += len(value)

            positions.append((tok_line, tok_lexpos))

        return positions

    def token(self):
        # Method required by ply.yacc to get the next token.
        try:
            category, value = next(self.iterator)
            # Instance a token for PLY
            tok = LexToken()
            tok.value = value
            tok.lineno, tok.lexpos = self.positions[self.index]
            self.index += 1
            
            if category == 'KEYWORD':
                tok.type = KEYWORD_MAP.get(value, value.upper())

            elif category == 'OPERATOR':
                tok.type = OPERATOR_MAP.get(value, 'OPERATOR')

            elif category == 'PUNCTUATION':
                tok.type = PUNCTUATION_MAP.get(value, 'PUNCTUATION')

            elif category == 'SPECIAL':
                tok.type = 'AMPERSAND' if value == '&' else 'SPECIAL'

            elif category == 'CONSTANT':
                tok.type = 'VALUE_NUM'

            elif category == 'LITERAL':
                stripped = value.strip()
                if stripped.startswith("'") and stripped.endswith("'"):
                    tok.type = 'VALUE_CHAR'
                else:
                    tok.type = 'TEXT_STRING'

            elif category == 'IDENTIFIER':
                if value == 'printf':
                    tok.type = 'PRINTF'
                elif value == 'scanf':
                    tok.type = 'SCANF'
                else:
                    tok.type = 'IDENTIFIER'

            else:
                tok.type = category

            return tok
            
        except StopIteration:
            # PLY stops parsing when token() returns None
            return None